/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Introduction to Physical AI',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-01-introduction',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: ROS 2 Architecture',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-02-ros2-architecture',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: ROS 2 Workspace',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-03-ros2-workspace',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: URDF & Robot Modeling',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-04-urdf-modeling',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 5: ROS 2 Control',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-05-ros2-control',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Chapter 6: Gazebo Simulation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-06-gazebo-simulation',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 7: Unity Simulation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-07-unity-simulation',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Chapter 8: Isaac Sim Introduction',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-08-isaac-sim-intro',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 9: Isaac Manipulation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-09-isaac-manipulation',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 10: Isaac Locomotion',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-10-isaac-locomotion',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Chapter 11: VLA Models',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-11-vla-models',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 12: VLA Training',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-12-vla-training',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chapter 13: VLA Deployment',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chapters/chapter-13-vla-deployment',
            },
          ],
        },
      ],
    },
    'deployment-guide',
  ],
};

module.exports = sidebars;
